name: cleanup
on:
  workflow_dispatch:
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'eu.pinske.playground.playground-java'
