# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven Repo
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Cache Maven Repo
      uses: actions/cache@v2
      with:
        path: src/main/frontend/node*
        key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-node
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag Docker image
      run: docker tag playground-java:0.1-SNAPSHOT apinske/playground-java
    - name: Push Docker image
      run: docker push apinske/playground-java
